name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Lint PHP files
        run: |
          find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l

      - name: Run self-tests
        run: php tests/run.php
